
ù	
opcode.protopb*ä	
Opcode
MSG_PING_PONG
	MSG_LOGIN
MSG_JOIN_TABLE
MSG_JOIN_TABLE_BROADCAST
MSG_LEAVE_TABLE
MSG_LEAVE_TABLE_BROADCAST
MSG_BREAK_BROADCAST
MSG_BREAK_BACK_BROADCAST
	MSG_READY	
MSG_READY_BROADCAST

MSG_DISMISS_ASK_BROADCAST
MSG_DISMISS_ANSWER 
MSG_DISMISS_ANSWER_BROADCAST
MSG_DISMISS_BROADCAST
MSG_GET_JU_CNT
MSG_GET_RESULT_DETAIL
MSG_RESULT_TOTAL
MSG_RESULT_PK
MSG_DINGQUE_ASK_BROADCAST
MSG_DINGQUE_ANSWER 
MSG_DINGQUE_ANSWER_BROADCAST
MSG_DINGPAO_ASK_BROADCAST
MSG_DINGPAO_ANSWER 
MSG_DINGPAO_ANSWER_BROADCAST
MSG_ROUND_START_BROADCASTe
MSG_ROUND_RESULT_BROADCASTf
MSG_DISPATCH_BROADCASTg
MSG_OUTh
MSG_OUT_BROADCASTi
MSG_OPERATE_ASK_BROADCASTj 
MSG_OPERATE_RESULT_BROADCASTk
MSG_OPERATEl
MSG_MINGLOUn
MSG_MINGLOU_BROADCASTo
MSG_MINGLOU_ASKp 
MSG_ROUND_DISPATCH_BROADCASTq
MSG_CHATx
MSG_CHAT_BROADCASTy
MSG_HISTORY_BROADCASTz
MSG_VOICE_TALK{
MSG_VOICE_TALK_BROADCAST|
MSG_CHAT_CUSTOM}
MSG_CHAT_CUSTOM_BROADCAST~
MSG_GVOICE_LOGIN
MSG_GVOICE_LOGIN_BROADCAST€
MSG_GAME_ENDç
MSG_SOCIAL_BEGINè
MSG_SOCIAL_ENDÏ
MSG_NET_BEGINÐ
MSG_NET_ENDÚ